language: ruby
rvm:
  - 2.2.5

services:
  - postgresql

before_script:
  - "psql -c 'create database travis;' -U postgres"
  - "bundle exec rake db:drop"
  - "bundle exec rake db:create"
  - "bundle exec rake db:migrate"
